### ISSUE TITLE
Media Source path not generated when using pdoPage Ajax pagination 

### ISSUE THREAD

**Issue by CouponCodeSwap** [promo360/fastuploadtv#17]
The Media Source path is not being generated when calling Template Variables using pdoTools pdoPage and using any of the Ajax pagination methods e.g. &ajaxMode=`scroll`. Only the path to the TV is generated. If I turn off ajaxMode, the Media Source path is generated when browsing to the next page of results and images display as expected. When MODX core File and Image input types for Template Variables are set, this is not an issue, so I think it is probably a bug with fastuploadtv. Note: I am processing images with pThumb.

For reference:

http://docs.modx.pro/en/components/pdotools/general-settings

**Comment by CouponCodeSwap** [comment]
I was able to fix this by modifying the plugin as follows:

`-    case 'OnWebPageInit':
        $mTypes = $modx->getOption('manipulatable_url_tv_output_types',null,'image,file').',fastuploadtv';
        $modx->setOption('manipulatable_url_tv_output_types', $mTypes);
        break;`

`+    case 'OnMODXInit':
        $mTypes = $modx->getOption('manipulatable_url_tv_output_types',null,'image,file').',fastuploadtv';
        $modx->setOption('manipulatable_url_tv_output_types', $mTypes);
        break;`

If there is a better way to go about this, please let me know.

**Comment by promo360** [comment]
Thank you! Your changes will be included in the next release 1.0.0-pl
